- name: playbook control useing ansible facts
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx in redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx in debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"