- name: play level variables
  hosts: local
  connection: local
  vars: 
    COURSE1: Devops
    DURATION2: 2 hrs
    TRAINER3: Sunil
  vars_files: 
  - course.yaml

  tasks:
  - name: print course information
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, course duration is {{ DURATION }} and trainer is {{ TRAINER }}"

  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, course duration is {{ DURATION }} and trainer is {{ TRAINER }}"