- name: play level variables
  hosts: local
  connection: local
  vars: 
    COURSE: Devops
    DURATION: 2 hrs
    TRAINER: Sunil

  tasks:
  - name: print course information
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, course duration is {{ DURATION }} and trainer is {{ TRAINER }}"

  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, course duration is {{ DURATION }} and trainer is {{ TRAINER }}"