- name: play level variables
  hosts: local
  connection: local

  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, course duration is {{ DURATION }} and trainer is {{ TRAINER }}"
